#!/bin/bash

changed_files=$(git diff --name-only --diff-filter=AM --staged)

if ! command -v clang-format; then
   echo "Could not find clang-format" >&2
   exit 1
fi

for i in ${changed_files}; do
   if [[ "$i" =~ .*\.(cpp|hpp) ]]; then
      clang-format -i "$i"
      git add "$i"
   fi
done

